[DIRECTORIES]
INCLUDES = "inc#"
FUNCTIONS = "inc#functions"
CLASSES = "inc#classes"
COMPONENTS = "inc#com"
MODULES = "inc#mod"
TEMPLATES = "inc#template"

[ADMIN_DIRECTORIES]
INCLUDES = "inc#"
FUNCTIONS = "inc#functions"
CLASSES = "inc#classes"
COMPONENTS = "inc#com"
MENUS = "inc#menus"


[WWW]
HTTP_SERVER = "http://b2b_sklep.localhost/"
HTTP_ROOT_CATALOG = ""
HTTP_INC_CATALOG = "inc_html/"
HTTP_CSS_CATALOG = "css/"
HTTP_JS_CATALOG = "js/"
HTTP_IMG_CATALOG = "img/"
HTTP_TEMPLATES_CATALOG = "templates/"

[ADMIN_WWW]
HTTP_SERVER = "http://b2b_sklep.localhost/"
HTTP_ROOT_CATALOG = "2panel/"
HTTP_INC_CATALOG = "inc_html/"
HTTP_CSS_CATALOG = "css/"
HTTP_JS_CATALOG = "js/"
HTTP_IMG_CATALOG = "img/"


[global]
session_store = "mysql"
#session_active = "1440"
session_active = "604800"
session_purge = "604800"


[DB]
server = "localhost"
port = "3306"
database = "b2b_sklep"
username = "b2b_sklep"
password = "b2b_sklep"
plink = "b2b_sklep"

[IMAGE]
SMALL_WIDTH = "64"
SMALL_HEIGHT = "64"
NORMAL_WIDTH = "800"
NORMAL_HEIGHT = "600"

[TABLES]
CORE_DB_ERRORS = "core_db_errors"
CORE_SESSIONS = "core_sessions"
CORE_TRANSLATION = "core_translation"
GLOBAL_ADMIN = "global_admin"
GLOBAL_RIGHTS2ADMIN = "global_rights2admin"
GLOBAL_RIGHTS = "global_rights"
GLOBAL_CURRENCES = "global_currences"
GLOBAL_CLIENT = "global_client"
GLOBAL_RIGHTS2CLIENT = "global_rights2client"
GLOBAL_CLIENT_USER = "global_client_user"
SHOP_CATEGORY = "shop_category"
SHOP_PRODUCT = "shop_product"
SHOP_PRODUCT_TO_CATEGORY = "shop_product_to_category"
SHOP_SHOPPING_BASKET = "shop_shopping_basket"
SHOP_SHOPPING_BASKET_PRODUCTS = "shop_shopping_basket_products"

[TEMPLATES]
admin = "admin.php"
shop = "shop"

[CFG_COM]
CATALOG = "catalog"
BASKET = "basket"
PRODUCT_INFO = "product_info"
LOGIN = "login"
LOGOUT = "logout"
