[DIRECTORIES]
INCLUDES = "inc#"
FUNCTIONS = "inc#functions"
CLASSES = "inc#classes"
COMPONENTS = "inc#com"
MODULES = "inc#mod"
TEMPLATES = "inc#template"

[ADMIN_DIRECTORIES]
INCLUDES = "inc#"
FUNCTIONS = "inc#functions"
CLASSES = "inc#classes"
COMPONENTS = "inc#com"
MENUS = "inc#menus"


[WWW]
;HTTP_SERVER = "http://sklep-b2b.pl/"
HTTP_SERVER = "http://ups_seller.sklep-b2b.pl/"
HTTP_ROOT_CATALOG = ""
HTTP_INC_CATALOG = "inc_html/"
HTTP_CSS_CATALOG = "css/"
HTTP_JS_CATALOG = "js/"
HTTP_IMG_CATALOG = "img/"
HTTP_TEMPLATES_CATALOG = "templates/"

[ADMIN_WWW]
HTTP_SERVER = "http://ups_seller.sklep-b2b.pl/"
HTTP_ROOT_CATALOG = "2panel/"
HTTP_INC_CATALOG = "inc_html/"
HTTP_CSS_CATALOG = "css/"
HTTP_JS_CATALOG = "js/"
HTTP_IMG_CATALOG = "img/"


[global]
session_store = "mysql"
;session_active = "1440"
session_active = "604800"
session_purge = "604800"

[DATE]
date = "Y-m-d"
datetime = "Y-m-d H:i"

[DB]
server = "sql.company.nazwa.pl"
port = "3307"
database = "company_20"
username = "company_20"
password = "***REMOVED***"
;server = "localhost"
;port = "3306"
;database = "b2b_sklep"
;username = "b2b_sklep"
;password = "b2b_sklep"
;plink = "b2b_sklep"
;server = "sql.company.nazwa.pl"
;port = "3306"
;database = "company"
;username = "company"
;password = "***REMOVED***"
;plink = "b2b_sklep"

[MAIL]
send_method = "mail"
;send_method = "smtp" (full PHPMailer) send_method_smtp_[host,user,login,type]
;send_method = "sendmail" send_method_sendmail_path
main_from_address = "orders@example.com"
main_from_name = "Sklep"
main_from_subject = "Wiadomość ze sklepu B2B"
;default_to_address = "orders@sklep.example.com"
default_to_address = "orders@example.com"
default_to_name = "Zamówienia"

[IMAGE]
SMALL_WIDTH = "64"
SMALL_HEIGHT = "64"
NORMAL_WIDTH = "800"
NORMAL_HEIGHT = "600"
SCRIPT = "img.php"
BUTTON_SCRIPT = "***REMOVED***"
BUTTON_SCRIPT_TEXT_PARAM = "t"

[TABLES]
CORE_DB_ERRORS = "core_db_errors"
CORE_SESSIONS = "core_sessions"
CORE_TRANSLATION = "core_translation"
GLOBAL_ADMIN = "global_admin"
GLOBAL_ARTICLE = "global_article"
GLOBAL_ARTICLE_CATEGORIES = "global_article_categories"
GLOBAL_RIGHTS2ADMIN = "global_rights2admin"
GLOBAL_RIGHTS = "global_rights"
GLOBAL_CURRENCES = "global_currences"
GLOBAL_CLIENT = "global_client"
GLOBAL_RIGHTS2CLIENT = "global_rights2client"
GLOBAL_CLIENT_USER = "global_client_user"
GLOBAL_CLIENT_USER_ADDRESS = "global_client_user_address"
GLOBAL_CLIENT_USER_ACCOUNT_MANAGER = "global_client_user_account_manager"
GLOBAL_CLIENT_ATTRIBUTES = "global_client_attributes"
GLOBAL_LOGIN_HISTORY = "global_login_history"
GLOBAL_PICTURES = "global_pictures"
GLOBAL_PICTURES_DATA = "global_pictures_data"
GLOBAL_TEMPLATE_PLACES = "global_template_places"
SHOP_CATEGORY = "shop_category"
SHOP_PRODUCT = "shop_product"
SHOP_PRODUCT_CLIENT_PRICE = "shop_product_client_price"
SHOP_PRODUCT_SUBTYPE = "shop_product_subtype"
SHOP_PRODUCT_TO_CATEGORY = "shop_product_to_category"
SHOP_PRODUCT_TO_CLIENT_USER = "shop_product_to_client_user"
SHOP_SHOPPING_BASKET = "shop_shopping_basket"
SHOP_SHOPPING_BASKET_HISTORY = "shop_shopping_basket_history"
SHOP_SHOPPING_BASKET_PRODUCT = "shop_shopping_basket_product"
SHOP_SHOPPING_BASKET_VERSION = "shop_shopping_basket_version"
SHOP_SHOPPING_BASKET_FAVORITE = "shop_shopping_basket_favorite"
;SHOP_SHOPPING_BASKET_FAVORITE = "shop_favorite_basket"
;SHOP_SHOPPING_BASKET_FAVORITE_PRODUCT = "shop_favorite_basket_product"
SHOP_ORDER = "shop_order"
SHOP_ORDER_ATTRIBUTES = "shop_order_attributes"
SHOP_ORDER_PRODUCT = "shop_order_product"
SHOP_ORDER_STATUS = "shop_order_status"
SHOP_ORDER_STATUS_HISTORY = "shop_order_status_history"
SHOP_ORDER_INVOICE = "shop_order_invoice"

[TEMPLATES]
admin = "admin.php"
;shop = "ups_seller"
shop = "ups_seller_o"
;shop = "zebra_o2"
;shop = "damen_shop"
mail = "damen_shop_mail"
jquery = "jquery-1.10.min.js"
jquery-ui = "jquery-ui.min.js"
pasmanteria_i_dodatki_krawieckie = 1
produkty_medyczne = 2

[CFG_COM]
CATALOG = "catalog"
BASKET = "basket"
BASKET_FAVORITE = "basket_favorite"
INVOICE = "invoice"
PRODUCT_INFO = "product_info"
LOGIN = "login"
LOGOUT = "logout"
ACCOUNT = "account"
ACCOUNT_PARAMETERS = "account_parameters"
ACCOUNT_LIST = "account_list"
ORDER_LIST = "order_list"
ORDER_BASKET = "order_basket"
ARTICLE = "article"
CONTACT = "contact"
SEARCH = "search"

[SHOP]
; default view for clients: product_with_client_price, product_with_client_price_only
;CLIENT_PRODUCT_PRICE_VIEW = "product_with_client_price"
;CLIENT_PRICE_MODE = "product_with_client_price_only"
CLIENT_PRICE_MODE = "show_all"
BASKET_SHOW_HISTORY = "false"
BASKET_SHOW_VERSIONS = "false"
BASKET_SHOW_LEVEL_UP = "false"
BASKET_SHOW_LEVEL_DOWN = "false"
BASKET_ORDER_ADDRESS_ADD = "true"
BASKET_ORDER_ADDRESS_PERSONAL_COLLECTION = "true"
BASKET_ORDER_ADDRESS_DEFAULT = "true"
ACCOUNT_MANAGER_DEFAULT = "true"
SHOW_CATALOG_ONLY_LOGGED = "true"
SHOW_COUNTS = "true"
SHOW_EMPTY = "false"

[DEFAULT]
XML_OUTPUT_ENCODING = "UTF-16"
XML_INPUT_ENCODING = "UTF-8"
PASSWORD_HASH_TYPE = "SH22";