<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://b2b_sklep.localhost/SOAP/scs.php" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="shop_control"
	targetNamespace="http://b2b_sklep.localhost/SOAP/scs.php">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://b2b_sklep.localhost/SOAP/scs.php">
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="getProductListRequest">
		<wsdl:part name="getProductListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getProductListResponse">
		<wsdl:part name="getProductListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientAddRequest">
		<wsdl:part name="doClientAddRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientAddResponse">
		<wsdl:part name="doClientAddResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getParamStartLengthRequest">
		<wsdl:part name="getParamStartLengthRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getParamStartLengthResponse">
		<wsdl:part name="getParamStartLengthResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientChangeRequest">
		<wsdl:part name="doClientChangeRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientChangeResponse">
		<wsdl:part name="doClientChangeResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientUserAddRequest">
		<wsdl:part name="doClientUserAddRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientUserAddResponse">
		<wsdl:part name="doClientUserAddResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientUserChangeRequest">
		<wsdl:part name="doClientUserChangeRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientUserChangeResponse">
		<wsdl:part name="doClientUserChangeResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientUserSetPasswordRequest">
		<wsdl:part name="doClientUserSetPasswordRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientUserSetPasswordResponse">
		<wsdl:part name="doClientUserSetPasswordResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientUserDeleteRequest">
		<wsdl:part name="doClientUserDeleteRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientUserDeleteResponse">
		<wsdl:part name="doClientUserDeleteResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientListRequest">
		<wsdl:part name="getClientListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientListResponse">
		<wsdl:part name="getClientListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientUserListRequest">
		<wsdl:part name="getClientUserListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientUserListResponse">
		<wsdl:part name="getClientUserListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doProductAddRequest">
		<wsdl:part name="doProductAddRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doProductAddResponse">
		<wsdl:part name="doProductAddResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doProductChangeRequest">
		<wsdl:part name="doProductChangeRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doProductChangeResponse">
		<wsdl:part name="doProductChangeResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setProductClientPriceRequest">
		<wsdl:part name="setProductClientPriceRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setProductClientPriceResponse">
		<wsdl:part name="setProductClientPriceResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doCategoryAddRequest">
		<wsdl:part name="doCategoryAddRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doCategoryAddResponse">
		<wsdl:part name="doCategoryAddResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doCategoryEditRequest">
		<wsdl:part name="doCategoryEditRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doCategoryEditResponse">
		<wsdl:part name="doCategoryEditResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doCategoryDeleteRequest">
		<wsdl:part name="doCategoryDeleteRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doCategoryDeleteResponse">
		<wsdl:part name="doCategoryDeleteResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setProduct2CategoryRequest">
		<wsdl:part name="setProduct2CategoryRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setProduct2CategoryResponse">
		<wsdl:part name="setProduct2CategoryResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getProductListFromCategoryRequest">
		<wsdl:part name="getProductListFromCategoryRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getProductListFromCategoryResponse">
		<wsdl:part name="getProductListFromCategoryResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getCategoryListRequest">
		<wsdl:part name="getCategoryListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getCategoryListResponse">
		<wsdl:part name="getCategoryListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getProductClientPriceListRequest">
		<wsdl:part name="getProductClientPriceListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getProductClientPriceListResponse">
		<wsdl:part name="getProductClientPriceListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getOrderListNewRequest">
		<wsdl:part name="getOrderListNewRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getOrderListNewResponse">
		<wsdl:part name="getOrderListNewResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getOrderListRequest">
		<wsdl:part name="getOrderListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getOrderListResponse">
		<wsdl:part name="getOrderListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setOrderStatusRequest">
		<wsdl:part name="setOrderStatusRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setOrderStatusResponse">
		<wsdl:part name="setOrderStatusResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setOrderHiddenStatusRequest">
		<wsdl:part name="setOrderHiddenStatusRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setOrderHiddenStatusResponse">
		<wsdl:part name="setOrderHiddenStatusResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientPriceProductListRequest">
		<wsdl:part name="getClientPriceProductListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientPriceProductListResponse">
		<wsdl:part name="getClientPriceProductListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setPictureRequest">
		<wsdl:part name="setPictureRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setPictureResponse">
		<wsdl:part name="setPictureResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setClientProductPriceListUpdateRequest">
		<wsdl:part name="setClientProductPriceListUpdateRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setClientProductPriceListUpdateResponse">
		<wsdl:part name="setClientProductPriceListUpdateResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientProductPriceListAddOrUpdateRequest">
		<wsdl:part name="doClientProductPriceListAddOrUpdateRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientProductPriceListAddOrUpdateResponse">
		<wsdl:part name="doClientProductPriceListAddOrUpdateResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doProductAddOrUpdateRequest">
		<wsdl:part name="doProductAddOrUpdateRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doProductAddOrUpdateResponse">
		<wsdl:part name="doProductAddOrUpdateResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doPictureAddOrUpdateRequest">
		<wsdl:part name="doPictureAddOrUpdateRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doPictureAddOrUpdateResponse">
		<wsdl:part name="doPictureAddOrUpdateResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doCategoryAddOrUpdateRequest">
		<wsdl:part name="doCategoryAddOrUpdateRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doCategoryAddOrUpdateResponse">
		<wsdl:part name="doCategoryAddOrUpdateResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setClientProductPriceListRequest">
		<wsdl:part name="setClientProductPriceListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setClientProductPriceListResponse">
		<wsdl:part name="setClientProductPriceListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getOrderHiddenStatusListRequest">
		<wsdl:part name="getOrderHiddenStatusListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getOrderHiddenStatusListResponse">
		<wsdl:part name="getOrderHiddenStatusListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientUserAddressAddOrUpdateRequest">
		<wsdl:part name="doClientUserAddressAddOrUpdateRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientUserAddressAddOrUpdateResponse">
		<wsdl:part name="doClientUserAddressAddOrUpdateResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientUserAddressDeleteRequest">
		<wsdl:part name="doClientUserAddressDeleteRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientUserAddressDeleteResponse">
		<wsdl:part name="doClientUserAddressDeleteResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientUserAddressListRequest">
		<wsdl:part name="getClientUserAddressListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientUserAddressListResponse">
		<wsdl:part name="getClientUserAddressListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientAddressListRequest">
		<wsdl:part name="getClientAddressListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientAddressListResponse">
		<wsdl:part name="getClientAddressListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getAddressListRequest">
		<wsdl:part name="getAddressListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getAddressListResponse">
		<wsdl:part name="getAddressListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientAttributeListRequest">
		<wsdl:part name="getClientAttributeListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientAttributeListResponse">
		<wsdl:part name="getClientAttributeListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientAttributeAddOrUpdateRequest">
		<wsdl:part name="doClientAttributeAddOrUpdateRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientAttributeAddOrUpdateResponse">
		<wsdl:part name="doClientAttributeAddOrUpdateResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getOrderAttributeListRequest">
		<wsdl:part name="getOrderAttributeListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getOrderAttributeListResponse">
		<wsdl:part name="getOrderAttributeListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doOrderAttributeAddOrUpdateRequest">
		<wsdl:part name="doOrderAttributeAddOrUpdateRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doOrderAttributeAddOrUpdateResponse">
		<wsdl:part name="doOrderAttributeAddOrUpdateResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getOrderInvoiceListRequest">
		<wsdl:part name="getOrderInvoiceListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getOrderInvoiceListResponse">
		<wsdl:part name="getOrderInvoiceListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientInvoiceListRequest">
		<wsdl:part name="getClientInvoiceListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientInvoiceListResponse">
		<wsdl:part name="getClientInvoiceListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getInvoiceListRequest">
		<wsdl:part name="getInvoiceListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getInvoiceListResponse">
		<wsdl:part name="getInvoiceListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doInvoiceAddOrUpdateRequest">
		<wsdl:part name="doInvoiceAddOrUpdateRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doInvoiceAddOrUpdateResponse">
		<wsdl:part name="doInvoiceAddOrUpdateResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setInvoiceStatusRequest">
		<wsdl:part name="setInvoiceStatusRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="setInvoiceStatusResponse">
		<wsdl:part name="setInvoiceStatusResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientAccountManagerListRequest">
		<wsdl:part name="getClientAccountManagerListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientAccountManagerListResponse">
		<wsdl:part name="getClientAccountManagerListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientAccountManagerAddOrUpdateRequest">
		<wsdl:part name="doClientAccountManagerAddOrUpdateRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientAccountManagerAddOrUpdateResponse">
		<wsdl:part name="doClientAccountManagerAddOrUpdateResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientUserAttributeListRequest">
		<wsdl:part name="getClientUserAttributeListRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="getClientUserAttributeListResponse">
		<wsdl:part name="getClientUserAttributeListResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientUserAttributeAddOrUpdateRequest">
		<wsdl:part name="doClientUserAttributeAddOrUpdateRequest" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="doClientUserAttributeAddOrUpdateResponse">
		<wsdl:part name="doClientUserAttributeAddOrUpdateResponse" type="xsd:string"></wsdl:part>
	</wsdl:message>
	<wsdl:portType name="shop_control">						<wsdl:operation name="getProductList">
			<wsdl:input message="tns:getProductListRequest"></wsdl:input>
			<wsdl:output message="tns:getProductListResponse"></wsdl:output>
		</wsdl:operation>
						<wsdl:operation name="doClientAdd">
							<wsdl:input
								message="tns:doClientAddRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doClientAddResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getParamStartLength">
							<wsdl:input
								message="tns:getParamStartLengthRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getParamStartLengthResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doClientChange">
							<wsdl:input
								message="tns:doClientChangeRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doClientChangeResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doClientUserAdd">
							<wsdl:input
								message="tns:doClientUserAddRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doClientUserAddResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doClientUserChange">
							<wsdl:input
								message="tns:doClientUserChangeRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doClientUserChangeResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doClientUserSetPassword">
							<wsdl:input
								message="tns:doClientUserSetPasswordRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doClientUserSetPasswordResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doClientUserDelete">
							<wsdl:input
								message="tns:doClientUserDeleteRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doClientUserDeleteResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getClientList">
							<wsdl:input
								message="tns:getClientListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getClientListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getClientUserList">
							<wsdl:input
								message="tns:getClientUserListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getClientUserListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doProductAdd">
							<wsdl:input
								message="tns:doProductAddRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doProductAddResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doProductChange">
							<wsdl:input
								message="tns:doProductChangeRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doProductChangeResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="setProductClientPrice">
							<wsdl:input
								message="tns:setProductClientPriceRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:setProductClientPriceResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doCategoryAdd">
							<wsdl:input
								message="tns:doCategoryAddRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doCategoryAddResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doCategoryEdit">
							<wsdl:input
								message="tns:doCategoryEditRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doCategoryEditResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doCategoryDelete">
							<wsdl:input
								message="tns:doCategoryDeleteRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doCategoryDeleteResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="setProduct2Category">
							<wsdl:input
								message="tns:setProduct2CategoryRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:setProduct2CategoryResponse">
							</wsdl:output>
						</wsdl:operation>						<wsdl:operation name="getProductListFromCategory">							<wsdl:input
								message="tns:getProductListFromCategoryRequest">
							</wsdl:input>							<wsdl:output
								message="tns:getProductListFromCategoryResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getCategoryList">
							<wsdl:input
								message="tns:getCategoryListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getCategoryListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getProductClientPriceList">
							<wsdl:input
								message="tns:getProductClientPriceListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getProductClientPriceListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getOrderListNew">
							<wsdl:input
								message="tns:getOrderListNewRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getOrderListNewResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getOrderList">
							<wsdl:input
								message="tns:getOrderListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getOrderListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="setOrderStatus">
							<wsdl:input
								message="tns:setOrderStatusRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:setOrderStatusResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="setOrderHiddenStatus">
							<wsdl:input
								message="tns:setOrderHiddenStatusRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:setOrderHiddenStatusResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getClientPriceProductList">
							<wsdl:input
								message="tns:getClientPriceProductListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getClientPriceProductListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="setPicture">
							<wsdl:input
								message="tns:setPictureRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:setPictureResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="setClientProductPriceListUpdate">
							<wsdl:input
								message="tns:setClientProductPriceListUpdateRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:setClientProductPriceListUpdateResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doClientProductPriceListAddOrUpdate ">
							<wsdl:input
								message="tns:doClientProductPriceListAddOrUpdateRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doClientProductPriceListAddOrUpdateResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doProductAddOrUpdate">
							<wsdl:input
								message="tns:doProductAddOrUpdateRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doProductAddOrUpdateResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doPictureAddOrUpdate">
							<wsdl:input
								message="tns:doPictureAddOrUpdateRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doPictureAddOrUpdateResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doCategoryAddOrUpdate">
							<wsdl:input
								message="tns:doCategoryAddOrUpdateRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doCategoryAddOrUpdateResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="setClientProductPriceList">
							<wsdl:input
								message="tns:setClientProductPriceListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:setClientProductPriceListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getOrderHiddenStatusList">
							<wsdl:input
								message="tns:getOrderHiddenStatusListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getOrderHiddenStatusListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doClientUserAddressAddOrUpdate">
							<wsdl:input
								message="tns:doClientUserAddressAddOrUpdateRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doClientUserAddressAddOrUpdateResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doClientUserAddressDelete">
							<wsdl:input
								message="tns:doClientUserAddressDeleteRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doClientUserAddressDeleteResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getClientUserAddressList">
							<wsdl:input
								message="tns:getClientUserAddressListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getClientUserAddressListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getClientAddressList">
							<wsdl:input
								message="tns:getClientAddressListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getClientAddressListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getAddressList">
							<wsdl:input
								message="tns:getAddressListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getAddressListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getClientAttributeList">
							<wsdl:input
								message="tns:getClientAttributeListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getClientAttributeListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doClientAttributeAddOrUpdate">
							<wsdl:input
								message="tns:doClientAttributeAddOrUpdateRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doClientAttributeAddOrUpdateResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getOrderAttributeList">
							<wsdl:input
								message="tns:getOrderAttributeListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getOrderAttributeListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doOrderAttributeAddOrUpdate">
							<wsdl:input
								message="tns:doOrderAttributeAddOrUpdateRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doOrderAttributeAddOrUpdateResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getOrderInvoiceList">
							<wsdl:input
								message="tns:getOrderInvoiceListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getOrderInvoiceListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getClientInvoiceList">
							<wsdl:input
								message="tns:getClientInvoiceListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getClientInvoiceListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getInvoiceList">
							<wsdl:input
								message="tns:getInvoiceListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getInvoiceListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doInvoiceAddOrUpdate">
							<wsdl:input
								message="tns:doInvoiceAddOrUpdateRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doInvoiceAddOrUpdateResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="setInvoiceStatus">
							<wsdl:input
								message="tns:setInvoiceStatusRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:setInvoiceStatusResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getClientAccountManagerList">
							<wsdl:input
								message="tns:getClientAccountManagerListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getClientAccountManagerListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doClientAccountManagerAddOrUpdate">
							<wsdl:input
								message="tns:doClientAccountManagerAddOrUpdateRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doClientAccountManagerAddOrUpdateResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="getClientUserAttributeList">
							<wsdl:input
								message="tns:getClientUserAttributeListRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:getClientUserAttributeListResponse">
							</wsdl:output>
						</wsdl:operation>
						<wsdl:operation name="doClientUserAttributeAddOrUpdate">
							<wsdl:input
								message="tns:doClientUserAttributeAddOrUpdateRequest">
							</wsdl:input>
							<wsdl:output
								message="tns:doClientUserAttributeAddOrUpdateResponse">
							</wsdl:output>
						</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="shop_control-SOAP" type="tns:shop_control">
		<soap:binding style="rpc"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="doClientChange">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="doClientAdd">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="doClientUserAdd">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="doClientUserChange">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="doClientUserDelete">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="doClientUserSetPassword">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getClientList">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getClientUserList">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="doProductAdd">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="doProductChange">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="setProductClientPrice">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="doCategoryAdd">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="doCategoryEdit">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="doCategoryDelete">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="setProduct2Category">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getProductList">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getProductListFromCategory">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getCategoryList">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getProductClientPriceList">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getOrderListNew">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getOrderList">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="setOrderStatus">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="setOrderHiddenStatus">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getParamStartLength">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getClientPriceProductList">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="setPicture">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="setClientProductPriceListUpdate">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="doClientProductPriceListAddOrUpdate ">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="doProductAddOrUpdate">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="doCategoryAddOrUpdate">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="doPictureAddOrUpdate">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="setClientProductPriceList">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getOrderHiddenStatusList">
			<soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
			<wsdl:input>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
      <wsdl:operation name="doClientUserAddressAddOrUpdate">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="doClientUserAddressDelete">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="getClientUserAddressList">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="getClientAddressList">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="getAddressList">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="getClientAttributeList">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="doClientAttributeAddOrUpdate">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="getOrderAttributeList">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="doOrderAttributeAddOrUpdate">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="getOrderInvoiceList">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="getClientInvoiceList">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="getInvoiceList">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="doInvoiceAddOrUpdate">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="setInvoiceStatus">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="getClientAccountManagerList">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="getClientUserAttributeList">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="doClientUserAttributeAddOrUpdate">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="doClientAccountManagerAddOrUpdate">
         <soap:operation soapAction="http://b2b_sklep.localhost/SOAP/scs.php" />
         <wsdl:input>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body namespace="http://b2b_sklep.localhost/SOAP/scs.php"
               use="literal" />
         </wsdl:output>
      </wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="shop_control">
		<wsdl:port binding="tns:shop_control-SOAP" name="shop_control-SOAP">
			<soap:address location="http://b2b_sklep.localhost/SOAP/scs.php" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
